export 'package:equatable/equatable.dart';
export 'package:flutter_readable/flutter_readable.dart' hide RContextMediaQuery,RContextLocalization;
export 'package:get/get.dart' hide  ContextExtensionss, Translations, Trans;
export 'package:playx_core/src/extensions/duration_extensions.dart';
export 'package:playx_core/src/extensions/string_extensions.dart';
export 'package:playx_core/src/playx_core.dart';
export 'package:playx_core/src/prefs/prefs.dart';
export 'package:playx_core/src/utils/app_scroll_behavior.dart';
export 'package:playx_core/src/utils/common_utils.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:playx_core/src/prefs/secure_prefs.dart';
export 'package:playx_core/src/prefs/secure_prefs_settings.dart';
export 'package:flutter_secure_storage/flutter_secure_storage.dart';
