export 'package:equatable/equatable.dart';
export 'package:flutter_readable/flutter_readable.dart' hide RContextMediaQuery;
export 'package:get/get.dart' hide Translations, ContextExtensionss;
export 'package:intl/date_symbol_data_local.dart';
export 'package:intl/intl.dart';
export 'package:playx_core/src/extensions/date_extensions.dart';
export 'package:playx_core/src/extensions/duration_extensions.dart';
export 'package:playx_core/src/extensions/num_extensions.dart';
export 'package:playx_core/src/extensions/string_extensions.dart';
export 'package:playx_core/src/playx_core.dart';
export 'package:playx_core/src/prefs/prefs.dart';
export 'package:playx_core/src/utils/app_scroll_behavior.dart';
export 'package:playx_core/src/utils/common_utils.dart';
export 'package:shared_preferences/shared_preferences.dart';
