name: Build
on:
  push:
    branches: [main , qa]
jobs:
  test:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - flutter-version: 3.24.0
            flutter-channel: stable
          - flutter-version: latest
            flutter-channel: stable
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - name: Install deps
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze lib test

      - name: Test
        run: flutter test --coverage

      - name: Check Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          min_coverage: 32
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: playx-flutter/playx_core
